[package]
name = "diesel_demo"
version = "0.1.0"
authors = ["Garrett Berg <gberg@neutral.io>"]

[dependencies]
diesel = "0.7.0"
diesel_codegen = { version = "0.7.0", default-features = false, features = ["postgres"] }
dotenv = "0.8.0"
dotenv_macros = "0.9.0"
